excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://clareese.github.io
title: Joyful Learners
tagline: learning made joyful
description: We envision a world where children are joyful about their learning. 
paginate: 5